//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_BORD_MST
    {
        public int BI_BOARD_NO_RUN { get; set; }
        public string BI_BOARD_NO { get; set; }
        public string BI_BOARD_MODEL { get; set; }
        public string LIFE_TIME { get; set; }
        public string LIFE_TIME_REAMIN { get; set; }
        public Nullable<System.DateTime> CYCLE_TIME { get; set; }
        public Nullable<System.DateTime> BI_BOARD_REGISTRATION_DATE { get; set; }
        public Nullable<System.DateTime> BI_BOARD_LAST_PM { get; set; }
        public Nullable<System.DateTime> BI_BOARD_NEXT_PM { get; set; }
        public Nullable<System.DateTime> BI_BOARD_LIFE_TIME { get; set; }
        public Nullable<int> BI_BOARD_LIFE_TIME_DAY { get; set; }
        public string BI_BOARD_STATUS { get; set; }
        public string BI_BOARD_OPARATE { get; set; }
    }
}
