//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_BOARD_PM_TRANS
    {
        public int BI_BOARD_TRANS_PM_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CYCLE_FLAG { get; set; }
        public string BI_BOARD_NO { get; set; }
        public string BI_BOARD_LAST_PM { get; set; }
        public string BI_BOARD_NEXT_PM { get; set; }
        public string EMP_UPDATE { get; set; }
    }
}
