//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_BOARD_TRANS
    {
        public int BI_BOARD_TRANS_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string HIST_CODE { get; set; }
        public string BI_MC_NO { get; set; }
        public string BI_RECIPE { get; set; }
        public string BI_BOARD_NO { get; set; }
    }
}
