//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_BOARD_MODEL_PRODUCT_MST
    {
        public int BI_BOARD_MODEL_NO { get; set; }
        public string BI_BOARD_MODEL { get; set; }
        public string BI_BOARD_COORDINATE_X { get; set; }
        public string BI_BOARD_COORDINATE_Y { get; set; }
        public string MAX_LIFE_TIME { get; set; }
        public string CYCLE_PERIOD_DAY { get; set; }
        public string CYCLE_PERIOD_TIME { get; set; }
        public string PRODUCT_TYPE { get; set; }
    }
}
