//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_MC_STATUS
    {
        public string BI_MC_NO { get; set; }
        public string BI_CHAMBER_NO { get; set; }
        public string BI_MODEL { get; set; }
        public string BI_SLOT_NO { get; set; }
        public string BI_SLOT_STATUS { get; set; }
        public string BI_BOARD_NO { get; set; }
    }
}
