//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_MC_RECIPE_MST
    {
        public string PRODUCT_TYPE { get; set; }
        public string TIME { get; set; }
    }
}
