//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_MC_CONDITION_DB_MST
    {
        public int CODITION_NO { get; set; }
        public string BI_MC { get; set; }
        public string TYPE_NAME { get; set; }
        public string PACKAGE { get; set; }
        public string PROGRAM_NAME { get; set; }
        public string BURN_IN_TIME { get; set; }
        public string BURN_IN_TEMP { get; set; }
        public string BURN_IN_BOARD_NAME { get; set; }
    }
}
