//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_OPERATION_TRANSACTION
    {
        public int TRANSACTION_ID { get; set; }
        public string LOT_EDP { get; set; }
        public string MC_NUMBER { get; set; }
        public string BOARD_NO { get; set; }
        public string TYPE_NAME { get; set; }
        public string STATUS_BI { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> START_BI_DATE { get; set; }
        public Nullable<System.DateTime> END_BI_DATE { get; set; }
        public string CREATE_BY { get; set; }
    }
}
