//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_PRODUCT_TYPE_LIST_MST
    {
        public int ID { get; set; }
        public string PRODUCT_TYPE_AXIS { get; set; }
        public string PRODUCT_TYPE_CONVERT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
    }
}
