//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BI_TRANSACTION_STATUS_MST
    {
        public int BI_TRANSACTION_STATUS { get; set; }
        public string BI_TRAN_STATUS_ID { get; set; }
        public string BI_TRANSATUS_NAME { get; set; }
    }
}
