//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BURN_INEntities : DbContext
    {
        public BURN_INEntities()
            : base("name=BURN_INEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BI_BOARD_MODEL_PRODUCT_MST> BI_BOARD_MODEL_PRODUCT_MST { get; set; }
        public virtual DbSet<BI_BOARD_PM_TRANS> BI_BOARD_PM_TRANS { get; set; }
        public virtual DbSet<BI_BOARD_SOCKET_MST> BI_BOARD_SOCKET_MST { get; set; }
        public virtual DbSet<BI_BOARD_SOCKET_STATUS_MST> BI_BOARD_SOCKET_STATUS_MST { get; set; }
        public virtual DbSet<BI_BOARD_STATUS_MST> BI_BOARD_STATUS_MST { get; set; }
        public virtual DbSet<BI_BOARD_TRANS> BI_BOARD_TRANS { get; set; }
        public virtual DbSet<BI_BORD_MST> BI_BORD_MST { get; set; }
        public virtual DbSet<BI_HIST_MST> BI_HIST_MST { get; set; }
        public virtual DbSet<BI_MC_CONDITION_DB_MST> BI_MC_CONDITION_DB_MST { get; set; }
        public virtual DbSet<BI_MC_MODEL_MST> BI_MC_MODEL_MST { get; set; }
        public virtual DbSet<BI_MC_MST> BI_MC_MST { get; set; }
        public virtual DbSet<BI_MC_RECIPE_MST> BI_MC_RECIPE_MST { get; set; }
        public virtual DbSet<BI_MC_STATUS> BI_MC_STATUS { get; set; }
        public virtual DbSet<BI_OPERATION_TRANSACTION> BI_OPERATION_TRANSACTION { get; set; }
        public virtual DbSet<BI_PRODUCT_TYPE_LIST_MST> BI_PRODUCT_TYPE_LIST_MST { get; set; }
        public virtual DbSet<BI_TRANSACTION_STATUS_MST> BI_TRANSACTION_STATUS_MST { get; set; }
        public virtual DbSet<sdt_member> sdt_member { get; set; }
    
        public virtual ObjectResult<sp_disply_maintain_board_master_Result> sp_disply_maintain_board_master()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_disply_maintain_board_master_Result>("sp_disply_maintain_board_master");
        }
    
        public virtual ObjectResult<sp_suggest_board_information_Result> sp_suggest_board_information()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_suggest_board_information_Result>("sp_suggest_board_information");
        }
    
        public virtual ObjectResult<sp_display_maintain_board_master_Result> sp_display_maintain_board_master()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_display_maintain_board_master_Result>("sp_display_maintain_board_master");
        }
    
        public virtual ObjectResult<sp_display_maintain_board_socket_Result> sp_display_maintain_board_socket()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_display_maintain_board_socket_Result>("sp_display_maintain_board_socket");
        }
    
        public virtual ObjectResult<sp_display_suggest_board_information_Result> sp_display_suggest_board_information()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_display_suggest_board_information_Result>("sp_display_suggest_board_information");
        }
    
        public virtual int sp_add_board_model_master(string bI_BOARD_MODEL, string pRODUCT_TYPE, string bI_BOARD_COORDINATE_X, string bI_BOARD_COORDINATE_Y)
        {
            var bI_BOARD_MODELParameter = bI_BOARD_MODEL != null ?
                new ObjectParameter("BI_BOARD_MODEL", bI_BOARD_MODEL) :
                new ObjectParameter("BI_BOARD_MODEL", typeof(string));
    
            var pRODUCT_TYPEParameter = pRODUCT_TYPE != null ?
                new ObjectParameter("PRODUCT_TYPE", pRODUCT_TYPE) :
                new ObjectParameter("PRODUCT_TYPE", typeof(string));
    
            var bI_BOARD_COORDINATE_XParameter = bI_BOARD_COORDINATE_X != null ?
                new ObjectParameter("BI_BOARD_COORDINATE_X", bI_BOARD_COORDINATE_X) :
                new ObjectParameter("BI_BOARD_COORDINATE_X", typeof(string));
    
            var bI_BOARD_COORDINATE_YParameter = bI_BOARD_COORDINATE_Y != null ?
                new ObjectParameter("BI_BOARD_COORDINATE_Y", bI_BOARD_COORDINATE_Y) :
                new ObjectParameter("BI_BOARD_COORDINATE_Y", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_board_model_master", bI_BOARD_MODELParameter, pRODUCT_TYPEParameter, bI_BOARD_COORDINATE_XParameter, bI_BOARD_COORDINATE_YParameter);
        }
    
        public virtual int sp_add_board_master(string bI_BOARD_NO, string bI_BOARD_MODEL, string bI_BOARD_REGISTRATION_DATE, string bI_BOARD_LAST_PM, string lIFE_TIME, string bI_BOARD_STATUS, string bI_BOARD_OPARATE)
        {
            var bI_BOARD_NOParameter = bI_BOARD_NO != null ?
                new ObjectParameter("BI_BOARD_NO", bI_BOARD_NO) :
                new ObjectParameter("BI_BOARD_NO", typeof(string));
    
            var bI_BOARD_MODELParameter = bI_BOARD_MODEL != null ?
                new ObjectParameter("BI_BOARD_MODEL", bI_BOARD_MODEL) :
                new ObjectParameter("BI_BOARD_MODEL", typeof(string));
    
            var bI_BOARD_REGISTRATION_DATEParameter = bI_BOARD_REGISTRATION_DATE != null ?
                new ObjectParameter("BI_BOARD_REGISTRATION_DATE", bI_BOARD_REGISTRATION_DATE) :
                new ObjectParameter("BI_BOARD_REGISTRATION_DATE", typeof(string));
    
            var bI_BOARD_LAST_PMParameter = bI_BOARD_LAST_PM != null ?
                new ObjectParameter("BI_BOARD_LAST_PM", bI_BOARD_LAST_PM) :
                new ObjectParameter("BI_BOARD_LAST_PM", typeof(string));
    
            var lIFE_TIMEParameter = lIFE_TIME != null ?
                new ObjectParameter("LIFE_TIME", lIFE_TIME) :
                new ObjectParameter("LIFE_TIME", typeof(string));
    
            var bI_BOARD_STATUSParameter = bI_BOARD_STATUS != null ?
                new ObjectParameter("BI_BOARD_STATUS", bI_BOARD_STATUS) :
                new ObjectParameter("BI_BOARD_STATUS", typeof(string));
    
            var bI_BOARD_OPARATEParameter = bI_BOARD_OPARATE != null ?
                new ObjectParameter("BI_BOARD_OPARATE", bI_BOARD_OPARATE) :
                new ObjectParameter("BI_BOARD_OPARATE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_board_master", bI_BOARD_NOParameter, bI_BOARD_MODELParameter, bI_BOARD_REGISTRATION_DATEParameter, bI_BOARD_LAST_PMParameter, lIFE_TIMEParameter, bI_BOARD_STATUSParameter, bI_BOARD_OPARATEParameter);
        }
    
        public virtual int sp_add_mc_master(string bI_MC_NO, string bI_MC_MODEL)
        {
            var bI_MC_NOParameter = bI_MC_NO != null ?
                new ObjectParameter("BI_MC_NO", bI_MC_NO) :
                new ObjectParameter("BI_MC_NO", typeof(string));
    
            var bI_MC_MODELParameter = bI_MC_MODEL != null ?
                new ObjectParameter("BI_MC_MODEL", bI_MC_MODEL) :
                new ObjectParameter("BI_MC_MODEL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_mc_master", bI_MC_NOParameter, bI_MC_MODELParameter);
        }
    
        public virtual int sp_add_mc_model_master(string bI_MC_MODEL, string bI_MC_CAPACITY_BOARD)
        {
            var bI_MC_MODELParameter = bI_MC_MODEL != null ?
                new ObjectParameter("BI_MC_MODEL", bI_MC_MODEL) :
                new ObjectParameter("BI_MC_MODEL", typeof(string));
    
            var bI_MC_CAPACITY_BOARDParameter = bI_MC_CAPACITY_BOARD != null ?
                new ObjectParameter("BI_MC_CAPACITY_BOARD", bI_MC_CAPACITY_BOARD) :
                new ObjectParameter("BI_MC_CAPACITY_BOARD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_add_mc_model_master", bI_MC_MODELParameter, bI_MC_CAPACITY_BOARDParameter);
        }
    
        public virtual int sp_update_product_type_list_mst()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_product_type_list_mst");
        }
    
        public virtual int sp_update_lifetime_board_mst()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_lifetime_board_mst");
        }
    
        public virtual ObjectResult<sp_display_transaction_operation_Result> sp_display_transaction_operation()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_display_transaction_operation_Result>("sp_display_transaction_operation");
        }
    
        public virtual int sp_update_operation_bi(string lOT_EDP, string mC_NUMBER, string tYPE_NAME, string fLAG_TRAN)
        {
            var lOT_EDPParameter = lOT_EDP != null ?
                new ObjectParameter("LOT_EDP", lOT_EDP) :
                new ObjectParameter("LOT_EDP", typeof(string));
    
            var mC_NUMBERParameter = mC_NUMBER != null ?
                new ObjectParameter("MC_NUMBER", mC_NUMBER) :
                new ObjectParameter("MC_NUMBER", typeof(string));
    
            var tYPE_NAMEParameter = tYPE_NAME != null ?
                new ObjectParameter("TYPE_NAME", tYPE_NAME) :
                new ObjectParameter("TYPE_NAME", typeof(string));
    
            var fLAG_TRANParameter = fLAG_TRAN != null ?
                new ObjectParameter("FLAG_TRAN", fLAG_TRAN) :
                new ObjectParameter("FLAG_TRAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_operation_bi", lOT_EDPParameter, mC_NUMBERParameter, tYPE_NAMEParameter, fLAG_TRANParameter);
        }
    
        public virtual ObjectResult<sp_login_axis_Result> sp_login_axis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_login_axis_Result>("sp_login_axis");
        }
    }
}
