//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace burn_in_app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sdt_member
    {
        public string ID { get; set; }
        public string NameEng { get; set; }
        public string SurnameEng { get; set; }
        public string NameThai { get; set; }
        public string SurnameThai { get; set; }
        public string Organize { get; set; }
        public string Position { get; set; }
        public string Email { get; set; }
        public string GlobalID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> GenerateDate { get; set; }
        public Nullable<int> Level { get; set; }
        public string Process { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
    }
}
